version: "3"

services:
  database:
    image: postgres:12.2
    container_name: "task-manager-database"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "task-manager"
    volumes:
      - database-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  database-postgres:
