version: "3"
services:

  postgres:
    image: postgres:12.2-alpine
    container_name: task-manager-db
    environment:
      POSTGRES_USER: "task-manager"
      POSTGRES_PASSWORD: "task-manager"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - network

volumes:
  postgres:

networks:
  network:
